#!/bin/bash

ARGS="$*"
DOMID=""
SERIAL=""
VIF=""

IFS=', ' read -r -a ARR <<< "$ARGS"

i=0
while [ $i -lt ${#ARR[@]} ]; do
    if [ "${ARR[$i]}" = "-xen-domid" ]; then
        let i=i+1
        DOMID=${ARR[$i]}
    fi
    if [ "${ARR[$i]}" = "-serial" ]; then
        let i=i+1
        SERIAL=${ARR[$i]}
    fi
    if [ "${ARR[$i]}" = "-netdev" ]; then
        let i=i+1
        # This definitely needs work
        VIF="-net tap,vlan=0,ifname=tap0,script=/usr/xen/bin/qemu-ifup"
    fi

    let i=i+1
done

XL_QMP_PATH="/var/run/xen/qmp-libxl-"
XL_QMP_PATH="$XL_QMP_PATH$DOMID"

# Keep hvmloader from dropping the ball on VGABios
xenstore-write /local/domain/$DOMID/hvmloader/bios "seabios"
xenstore-write /local/domain/$DOMID/hvmlooder/seabios-legacy-load-roms "1"

/usr/bin/qemu-system-i386 -xen-domid $DOMID -nodefaults -name qemu-3.0 -machine xenfv,max-ram-below-4g=0xf0000000 -m 1024 -vga std -display surfman -drive file=/dev/xen/blktap-2/tapdev0,if=ide,index=0,media=disk,format=raw,readonly=off -chardev socket,id=libxl-cmd,path=$XL_QMP_PATH,server,nowait -qmp unix:$XL_QMP_PATH,server,nowait $SERIAL $VIF
